server:
  port: 8081
spring:
  application:
    name: spring-boot-example
  profiles:
    active: '@profiles.active@'
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 2000MB
      file-size-threshold: 0
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
    typeEnumsPackage: com.ymyang.enums
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enable: true
  markdowns: classpath*:swagger-markdown/*
  basic:
    username: root
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"
