spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_test_storage?useSSL=false&autoReconnect=true&failOverReadOnly=false&useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

## mysql逆向生成配置
generator:

  # 作者，会标注接口文档的负责人
  author: ymyang

  # 邮箱
  email: ymyang@163.com

  # 当前应用的微服务应用名，会标注在Feign Client上
  applicationName: account-service

  # 是否文件覆盖
  overwrite: false

  # 控制器增加shiro权限注解
  shiroAnnotation: true

  # 控制器所属modules绝对路径，若path和packageName为空时，则不生成，最终目录：${controllerPath}/src/main/java/${controllerPackageName}/${modulesName}
  controllerPath: D:/work/framework/examples/spring-cloud-example/storage-service
  controllerPackageName: com.ymyang.controller

  # 控制器中的查询参数对象，若path和packageName为空时，则不生成，最终目录：${queryParamPath}/src/main/java/${queryParamPackageName}/${modulesName}
  queryParamPath: D:/work/framework/examples/spring-cloud-example/common
  queryParamPackageName: com.ymyang.param

  # 控制器中的新建参数对象，若path和packageName为空时，则不生成，最终目录：${createParamPath}/src/main/java/${createParamPackageName}/${modulesName}
  createParamPath: D:/work/framework/examples/spring-cloud-example/common
  createParamPackageName: com.ymyang.param

  # 控制器中的更新参数对象，若path和packageName为空时，则不生成，最终目录：${updateParamPath}/src/main/java/${updateParamPackageName}/${modulesName}
  updateParamPath: D:/work/framework/examples/spring-cloud-example/common
  updateParamPackageName: com.ymyang.param

  # 控制器中的返回值对象，若path和packageName为空时，则不生成，最终目录：${dtoPath}/src/main/java/${dtoPackageName}/${modulesName}
  dtoPath: D:/work/framework/examples/spring-cloud-example/common
  dtoPackageName: com.ymyang.dto

  # service所属modules绝对路径，若path和packageName为空时，则不生成，最终目录：${servicePath}/src/main/java/${servicePackageName}/${modulesName}
  servicePath: D:/work/framework/examples/spring-cloud-example/storage-service
  servicePackageName: com.ymyang.service

  # 实体类，若path和packageName为空时，则不生成，最终目录：${entityPath}/src/main/java/${entityPackageName}/${modulesName}
  entityPath: D:/work/framework/examples/spring-cloud-example/storage-service
  entityPackageName: com.ymyang.entity

  # mybatis mapper类，若path和packageName为空时，则不生成，最终目录：${mapperPath}/src/main/java/${mapperPackageName}/${modulesName}
  mapperPath: D:/work/framework/examples/spring-cloud-example/storage-service
  mapperPackageName: com.ymyang.mapper

  # feign客户端，若path和packageName为空时，则不生成，最终目录：${feignClientPath}/src/main/java/${feignClientPackageName}/${modulesName}
  feignClientPath:
  feignClientPackageName:

  # 菜单sql 最终目录：${menuSqlPath}/src/main/resources/sql/${modulesName}
  menuSqlPath:

  # 表前缀
  tablePrefix: t_

  modules:
    # 模块名
    - name: storage
      # 需要生成的表名列表
      tables:
        - t_storage